# Generated by Django 5.1.2 on 2024-10-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos_inves', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('tipo_publicacion', models.CharField(choices=[('Artículo', 'Artículo'), ('Libro', 'Libro')], max_length=100)),
                ('categoria', models.CharField(choices=[('Ciencia', 'Ciencia'), ('Tecnología', 'Tecnología'), ('Humanidades', 'Humanidades')], max_length=100)),
                ('palabras_clave', models.CharField(max_length=255)),
                ('grupo_investigacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grupos_inves.grupoinvestigacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
